name: Deploy to @lvksh/signal

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - name: Build
        run: npm run build
      - uses: vimtor/action-zip@v1
        with:
          files: build/
          dest: result.zip
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://signal.lvksh.cloud/deployments/push?site=987654320'
          method: 'PUT'
          bearerToken: ${{ secrets.SIGNAL_TOKEN }}
          files: '{ "data": "${{ github.workspace }}/result.zip" }'