name: Deploy to Edgeserver

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: "🚚 Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - name: Build
        run: npm run build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-upload@master
        with:
          app_id: 987654319
          server: https://app.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: build